metalabdesign/midori

package.json

The `useragent` module requires `yamlparser` to be installed under certain situations.
See https://github.com/3rd-Eden/useragent#api

Add `yamlparser` dependency.

---

src/middleware/render.js
src/middleware/send.js
test/spec/middleware/send.spec.js

Render middleware is no longer responsible for calling `res.end`.

Create send middleware.

---

src/middleware/header.js
test/spec/middleware/header.spec.js

Takes two arguments, header name, and value. Value can be a string, a promise, or a function that operates on `req` and returns a string or promise. If a falsy value is returned, header is not set.

Minimal header middleware.

---

src/middleware/status.js
test/spec/middleware/status.spec.js

The argument to `status` can be an int, a promise resolving to an int, or a function that operates on req and returns an int or promise resolving to an int.

Minimal status code middleware.

---

package.json
src/middleware/assets.js

* Use more aptly named env var `HAS_WEBPACK_STATS_EVENTS`.
* Only read assets if they exist, warn only if they're actually needed.
* Upgrade to latest `webpack-assets`.
The `exists` check prevents the development server from crashing when it can't find any assets.

Make `assets` middleware slightly smarter.

---

example/http.js
example/match.js
example/verbs.js
package.json
src/adapter/http.js
src/middleware/match.js
src/middleware/match/method.js
src/middleware/match/path.js
src/middleware/match/query.js
src/middleware/match/util.js
src/middleware/match/verbs.js
src/middleware/tap.js
test/script/spec.sh
test/spec/middleware/match/method.js
test/spec/middleware/match/path.spec.js
test/spec/middleware/match/query.spec.js
test/spec/middleware/match/verbs.spec.js
test/spec/middleware/tap.spec.js

You can now match against urls, query strings, HTTP methods and any other request-based conditional you can think of.
```javascript
const createApp = match(matcher, createIfApp, createElseApp);
```
Creates a new app that:
* if `matcher` passes, the request chain passes to `ifApp`,
* otherwise, the request chain passes to `elseApp`.
The `matcher` is like standard middleware, except instead of returning an object with `request`, it returns an object with `matches(req, res) => boolean` which is used by `matches` to determine which branch to take.
By virtue of the fact `matcher` is (almost) normal middleware, a composition of matchers can be created:
```javascript
const createApp = match(compose(matcherA, matcherB), createIfApp, createElseApp);
```
Standard matchers are available for:
* HTTP …

Support for matching.

---

example/thunk.js
src/middleware/thunk.js
test/spec/middleware/thunk.spec.js

This is essentially the `apply` method of an applicative.
Sometimes you want to change the processing mechanism of your application at runtime instead of construction time. For example:
```javascript
const app = compose(
match(path('/foo'), send())
);
```
This app structure is static. That app will always match `/foo` to `send()`. What if we wanted the structure of the app to be the result of a function instead? For example, swapping between a random app per request or using routes from a database? Such a thing is now possible in relatively elegant fashion:
Swapping between two apps:
```javascript
const createApp = compose(
thunk((app) => {
const a = send('Hello')(app);
const b = send('World')(app);
return () => {
return (Math.random() > 0.5) ? a : b;
};
})
);
```
Updating routes at …

Add `thunk` middleware.

---

example/proxy.js
package.json
src/middleware/proxy.js
test/spec/middleware/proxy.spec.js

Now you can pipe requests to other servers. The initial implementation is intentionally simple – you can't adjust anything other than the options passed into the proxy request handler (i.e. `{ target: 'http://www.google.ca'; }`). This will probably change in the future.
/cc @nealgranger

Support for `proxy` middleware. 

---

src/middleware/match/path.js
test/spec/middleware/match/path.spec.js

If `/` remains as a token you end up with a tokens array of `['/', '/foo', ...]` this will only match the path `//foo`. By stripping the tokens if the path is `/` the problem is solved.
/cc @nealgranger

Ignore tokens for path matches against `/`.

---

src/middleware/redirect.js
test/spec/middleware/redirect.spec.js

Let's you send your users somewhere else! Basically shorthand for setting the HTTP status code, adding a location header and ending the request. Can be invoked with either a function generating the new location or a string.
e.g.
```javascript
redirect(() => '/foo');
```
or
```javascript
redirect('/foo');
```
/cc @nealgranger

Add redirect middleware.

---

src/serve.js

This is useful for the error handler to actually do something with the response.
/cc @nealgranger

Pass `req` and `res` to `serve` error handler.

---

package-lock.json
package.json
src/serve.js
test/spec/logging.spec.js
test/spec/serve.spec.js
test/spec/timing.spec.js

This allows for doing other processing instead of just sending back the 404 response. Additionally, error handling has been brought back and any errors encountered in `serve` will be propagated into the pipeline.

Allow resuming request pipeline when file not found in `serve`.

---

src/internal/baseApp.js
test/spec/internal/baseApp.spec.js

There isn't really a "catch-all" like `res.finished` for the `upgrade` event. So if we're the only listener then we know we can close the connection. Otherwise we just pray whomever else has attached to the event knows what they're doing. Such is the case when using things like `socket.io`.

Prevent `upgrade` default handler with other listeners present.

---

src/match/path.js
src/serve.js
test/spec/match/path.spec.js
test/spec/serve.spec.js

In `express` the value of `req.path` is read-only and setting it will blow things up.

Rename `path` to `baseUrl` for path matching.

---

.babelrc
.eslintignore
.gitignore
README.md
package-lock.json
package.json
src/test/fetch.js
src/test/index.js
test/spec/send.spec.js
test/spec/serve.spec.js
test/spec/test/fetch.spec.js

The `fetch` utility can be used to test your `midori` apps easily without having to spin up a dedicated server for every test. It works mostly like the usual what-wg `fetch` except it takes a midori app or app creator as its first argument and the promise result is closer to a node `ServerResponse` than anything else. Usage highlights can be found in `send.spec.js` and `server.spec.js` for now, as those two relied most heavily on the actual body content of the response.
Example:
```js
import {request, next} from 'midori';
import {fetch} from 'midori/test';
const baseApp = request((req, res) => {
res.setHeader('Content-Type', 'test');
return next;
});
return fetch(baseApp, '/').then((res) => {
assert(res.headers['content-type'] === 'test');
});
```

Add `fetch` testing utility.

---

example/pending.js
src/index.js
src/pending.js
test/spec/pending.spec.js

Pending allows you to wait for a given trigger before continuing the request chain. If this condition is not met within the given timeout then the `onTimeout` app is used instead. If the condition is met then the current app can be replaced.
Example:
```javascript
import {send, use, compose, request, pending} from '../src';
import {parse} from 'qs';
import url from 'parseurl';
const waits = [];
// In one browser tab go to /wait
// In another browser tab go to /unwait?name=Fred
const createApp = compose(
use('/wait', pending((fn) => {
waits.push(fn);
})),
use('/unwait', request((req) => {
const query = parse(url(req).query);
const next = send(`Hello ${query.name}`);
waits.forEach((fn) => {
fn(next);
});
waits.length = 0;
return send('It is done.');
})),
);
const app = createApp(); …
```

Add new `pending` utility.

---

src/proxy.js
test/spec/proxy.spec.js

You can use these to do body rewriting or similar such things.
```javascript
proxy({
target: 'http://foo.com',
onResponse: (res) => {
if (res.statusCode === 302) {
const string = 'hello';
const body = bl(string);
res.statusCode = 200;
res.statusMessage = 'OK';
res.headers['content-length'] = string.length;
res.pipe = body.pipe.bind(body);
res.destroy();
}
},
})
```

Allow access to `proxyReq` and `proxyRes` events.

---

src/pending.js
test/spec/pending.spec.js

Allow users to define an action that occurs when the `pending` result has completed whether from error, user request abort or resolution. This is often useful for removing listeners that were previously attached.

Support `dispose` behaviour in `pending`.

---

src/connect.js
src/listening.js
src/types.js
test/spec/connect.spec.js
test/spec/listening.spec.js

If you connect an app that has a `listening` handler you would expect this to be called if the server is listening. I guess this deviates from the normal spec a little but this feels largely like intended behaviour. Especially if you wish to do things like setup or teardown.
Will have to think on this a bit.

Invoke `listening` if server is already listening.

---

src/test/fetch.js
test/spec/test/fetch.spec.js

Does what it says on the box. Some people access `req.on('close', ...)` and this allows for that to be tested without anything blowing up.

Bubble test `on` and `once` for request objects.

---

README.md
src/createSelector.js
src/internal/isSelector.js
src/request.js
src/response.js
src/test/createMockRequest.js
src/test/createMockResponse.js
src/test/fetch.js
src/test/getSelectorImplementation.js
src/test/index.js
src/test/runSelector.js
src/upgrade.js
test/spec/test/runSelector.spec.js

* Add `createMockRequest`, `createMockResponse` test functions.
* Add `runSelector` and `getSelectorImplementation` test functions.
Instead of running through the entire request lifecycle, `runSelector` allows you to just test the value and execution of a single selector, while mocking out all the selectors it depends on. Examples and usage can be found in the README. `createMockRequest` and `createMockResponse` have been extracted to allow the mocking of the `request` "selector".

Allow mocking of selectors during tests.

---

src/internal/error/requestErrorHandler.js

Apparently naming it `console` makes new version of `eslint` complain.

Rename `console` to `consoleObject`.
