metalabdesign/midori

- .npmignore
So the right stuff actually goes out.
> Add `.npmignore` for publishing.

- .eslintignore
- .travis.yml
- package.json
- src/base.js
- src/middleware/assets.js
- src/middleware/empty.js
- src/middleware/react.js
- src/react.js
- src/webpack.js
- test/spec/middleware/id.spec.js
Does what it says on the box. Now with support for `adana` and native modules during the CI phase. Tests passing are always a good thing.
> Support for TravisCI, `lodash@4` and latest `eslint` rules.

- .gitignore
- .npmignore
- package.json
Cause coverage is a good thing™.
> Add `adana` packages for reporting coverage.

- package.json
> Version bump to v0.1.2.

- package.json
- src/middleware/assets.js
The `name` property is not consistently present on assets.
> Fix assets middleware.

- src/middleware/render.js
Add missing entry in callback chain.
> Fix render result.

- package.json
> Version bump to v0.2.2.

- src/middleware/render.js
- test/spec/middleware/render.spec.js
Add render middleware tests.
Fix promise error handling bug.
Rename local parameters.
> Render tests

- test/spec/adapter/express.spec.js
- test/spec/adapter/hapi.spec.js
Nothing fancy, but it hits the branches.
> Add error tests for `hapi` and `express`.

- src/middleware/send.js
- test/spec/middleware/send.spec.js
The argument to `send` can be a string, a promise, or a function that operates on `req` and returns a string or promise.
> Update send middleware to accept promises.

- package.json
> Version bump to v0.2.3.

- package.json
> Version bump to v0.2.4.

- package.json
> Version bump to v0.2.5.

- package.json
> Version bump to v0.3.0.

- package.json
> Version bump to v0.3.1.

- package.json
> Version bump to v0.3.2.

- package.json
> Version bump to v0.3.3.

- package.json
> Version bump to v0.3.5.

- package.json
> Version bump to v0.4.0.

- package.json
> Version bump to v0.4.1.

- src/internal/baseApp.js
- src/internal/errorHandler.js
- test/spec/internal/baseApp.spec.js
> Fix `headerSent` to `headersSent`.

- package.json
> Version bump to v0.4.2.

- package.json
> Version bump to v0.4.3.

- package.json
> Version bump to v0.4.4.

- src/logging.js
- test/spec/logging.spec.js
What was `req` should have been `res`.
> Include `statusCode` in logs and make better log test.

- .npmignore
> Add `web` to `.npmignore`.

- src/query.js
- test/spec/query.spec.js
> Fix extra `?` being parsed in `query`.

- flow-typed/npm/styled-components_v3.x.x.js
- package-lock.json
- package.json
- src/apply.js
- src/compose.js
- src/compression.js
- src/createSelector.js
- src/internal/baseApp.js
- src/listen.js
- src/match/query.js
- src/proxy.js
- src/send.js
- src/test/fetch.js
- test/spec/match/query.spec.js
- web/src/component/base/Grid/Grid.js
- web/src/component/base/Link/Link.js
🎉 Fixed version of https://github.com/metalabdesign/midori/pull/98.
> Update `flow-bin` to `0.83.0`.
